// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYUOjdm74fQiTbzmjZ_HXHhli4kGr75EQ',
    appId: '1:161148782686:web:29f638eabc669ea6754ccf',
    messagingSenderId: '161148782686',
    projectId: 'renasya-fb',
    authDomain: 'renasya-fb.firebaseapp.com',
    storageBucket: 'renasya-fb.appspot.com',
    measurementId: 'G-WPLECL0ZM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2XnpGFarWBiDHxQJiIFkIkOWCKDrLQYg',
    appId: '1:161148782686:android:778c54b8850e67a4754ccf',
    messagingSenderId: '161148782686',
    projectId: 'renasya-fb',
    storageBucket: 'renasya-fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsTjbkfHueNe6ECmBK0eWHur4tzR7tKwA',
    appId: '1:161148782686:ios:bebac5bc78475cf1754ccf',
    messagingSenderId: '161148782686',
    projectId: 'renasya-fb',
    storageBucket: 'renasya-fb.appspot.com',
    iosBundleId: 'com.example.renasyaFb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsTjbkfHueNe6ECmBK0eWHur4tzR7tKwA',
    appId: '1:161148782686:ios:8dfc9437beb06d98754ccf',
    messagingSenderId: '161148782686',
    projectId: 'renasya-fb',
    storageBucket: 'renasya-fb.appspot.com',
    iosBundleId: 'com.example.renasyaFb.RunnerTests',
  );
}
